### ISSUE TITLE
新闻标题溢出的时候文本会重叠

### ISSUE THREAD

**Issue by yzhang-gh** [dr2009/stylish-ithome#3]
### 不用样式

![b](https://cloud.githubusercontent.com/assets/7588612/25610751/049b0d48-2f57-11e7-86a6-a89ff1987a5e.png)

### 用样式

![a](https://cloud.githubusercontent.com/assets/7588612/25610695/d0c2ab34-2f56-11e7-8ae2-a135ad0f8714.png)

**Comment by dr2009** [comment]
多谢,已修复 #4
